name: CI-Test-demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: windows-2019
    steps:
      - name: Checkout repo
        uses: actions/checkout@v1

      - name: Install Office
      #   # run: choco install office365business
      #   # run: choco install office365business --params="'/productid:O365HomePremRetail /exclude:Access Excel PowerPoint Groove Lync OneDrive OneNote Outlook Publisher /eula:FALSE'"
        run: choco install microsoft-office-deployment --params="'/64bit /Product:WordRetail /DisableUpdate:True'"

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
          cache: 'pip'
      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel
          pip install robotframework robotframework-seleniumlibrary rpaframework-windows webdrivermanager rpaframework-core rpaframework-dialogs

      - name: Serve HTTP page in localhost:8080 as background process
        run: |
          cmd /c "START /b run_local_http_server.bat"
          powershell -command "Start-Sleep -s 5"

      - name: Webdrivemanager install chromedriver
        run: webdrivermanager chrome

      - name: Robot Framework Word Tests
        run: robot -N "PoC Tests - Shiny-Octo-Doodle" -d Results -i Word .\Tests

      - name: Robot Framework HTML Tests
        run: robot -N "PoC Tests - Shiny-Octo-Doodle" -d Results -i HTML .\Tests

      - name: Send mail with reports
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          # Required mail server address:
          server_address: smtp.office365.com
          # Required mail server port:
          server_port: 587
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWD}}
          # Required mail subject:
          subject: Github Actions test job result
          # Required recipients' addresses:
          to: jonathan.martino@propylon.com
          # Required sender full name (address can be skipped):
          from: Github Actions Bot # <user@example.com>
          # Optional plain body:
          body: Build job of ${{github.repository}} result
          # Optional unsigned/invalid certificates allowance:
          ignore_cert: true
          # # Optional converting Markdown to HTML (set content_type to text/html too):
          # convert_markdown: true
          # Optional attachments:
          attachments: ./Results/*.*